package com.bignerdranch.android.escapeovatortemp;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageButton;

public class Floor5Activity extends ParentFloorActivity {
    private static final String TAG = "Floor5Activity";



    public static Intent newIntent(Context packageContext){
        Intent intent = new Intent(packageContext, Floor5Activity.class);
        return intent;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_floor5);

        mGrabXRayGlassesButton = (ImageButton) findViewById(R.id.grab_xrayglasses);
        mGrabXRayGlassesButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mXRayGlassesHeld = true;
                updateToolbar();

                // Start the noteActivity with the auto-generated note
                Intent i = NoteActivity.newIntent(Floor5Activity.this, Floor1Activity.sAutoGeneratedNotes.get(4).getId(), 5);
                startActivity(i);
            }
        });

        updateToolbar();
    }

    @Override
    protected void onStart(){
        super.onStart();
        Log.d(TAG, "onStart() called");
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d(TAG, "onResume() called");
    }

    @Override
    protected void onPause() {
        super.onPause();
        Log.d(TAG, "onPause() called");
    }

    @Override
    protected void onStop() {
        super.onStop();
        Log.d(TAG, "onStop() called");
        Intent intent = new Intent(Floor5Activity.this, ElevatorFragment.class);
        startActivity(intent);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.d(TAG, "onDestroy() called");
    }
}
