package com.bignerdranch.android.finalproject;

import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.RecyclerView;
import android.view.Menu;
import android.view.View;
import android.widget.TextView;

import java.util.List;

public class MenuActivity extends AppCompatActivity {

    private List<Note> playerNotes; //stores all the notes, generated by the game or the player

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_menu);


    }

    private class NoteHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
        private TextView floorTextView;
        private TextView noteTextView;
        private Note note;

        public NoteHolder(View itemView) {
            super(itemView);
        }


        //use this to launch into the note editor activity
        @Override
        public void onClick(View v) {
            Intent intent = NoteActivity.newIntent(MenuActivity.this, note.getId());
            startActivity(intent);
        }
    }
}